package com.twitter.pers.util;


import java.rmi.Remote;
import java.rmi.RemoteException;
import java.util.ArrayList;

/**
 * Very simple service that reads a file generated by namedatacreator.cpp:
 * each name is of fixed length and is at file in position vertex-id * length.
 * @author Aapo Kyrola, akyrola@twitter.com
 */
public interface RemoteVertexNameService extends Remote {

    public ArrayList<String> namify(ArrayList<Integer> ids) throws RemoteException;

}
